// react-draw-sequence/src/components/UploadSummary.js
import React from "react";

export default class UploadSummary extends React.Component {
  constructor(props) {
    super(props);

    this.isRecognizedTextEmpty = this.isRecognizedTextEmpty.bind(this);
    this.recognizedTextMessage = this.recognizedTextMessage.bind(this);
    this.recognizedTextClass = this.recognizedTextClass.bind(this);
  }

  isRecognizedTextEmpty() {
    return (
      !this.props.result.recognizedText ||
      this.props.result.recognizedText === ""
    );
  }

  recognizedTextMessage() {
    if (this.isRecognizedTextEmpty()) {
      return "No text has been recognized.";
    } else {
      return `Recognized text: "${this.props.result.recognizedText}"`;
    }
  }

  recognizedTextClass() {
    const baseClass = "alert summary-alert ";

    if (!this.props.result) {
      return baseClass;
    } else {
      if (this.props.result.succeeded) {
        return baseClass + "alert-success";
      } else {
        if (this.props.result.isRecognizedTextEmpty) {
          return baseClass + "alert-warning";
        } else {
          return baseClass + "alert-danger";
        }
      }
    }
  }

  render() {
    if (this.props.result) {
      const messages = this.props.result.errors.map((err, i) => (
        <li key={i}>{err}</li>
      ));
      return (
        <div className="mb-2 text-center">
          <ul> {messages} </ul>
          <p className={this.recognizedTextClass()}>
            {this.recognizedTextMessage()}
          </p>
        </div>
      );
    } else {
      return null;
    }
  }
}

// DrawSequence/ClientApp/partials/UploadSummary.vue
<template>
  <div v-if="result" class="mb-2 text-center">
    <ul>
      <li v-for="(message, index) in result.errors" :key="index">
        {{ message }}
      </li>
    </ul>
    <p class="alert" :class="recognizedTextClass">
      {{ recognizedTextMessage }}
    </p>
  </div>
</template>

<script>
export default {
  computed: {
    isRecognizedTextEmpty: function() {
      return !this.result.recognizedText || this.result.recognizedText === "";
    },
    recognizedTextMessage: function() {
      if (this.isRecognizedTextEmpty) {
        return "No text has been recognized.";
      } else {
        return `Recognized text: "${this.result.recognizedText}"`;
      }
    },
    recognizedTextClass: function() {
      if (!this.result) {
        return "";
      } else {
        if (this.result.succeeded) {
          return "alert-success";
        } else {
          if (this.isRecognizedTextEmpty) {
            return "alert-warning";
          } else {
            return "alert-danger";
          }
        }
      }
    }
  },
  props: {
    result: {
      required: false,
      default: null
    }
  }
};
</script>

<style scoped>
p {
  max-width: 60%;
  margin: 0 auto;
}
</style>
