// react-draw-sequence/src/components/Navigation.js
import React from "react";
import { NavLink } from "react-router-dom";
import styles from './../styles/navigation.module.css';

export default class Navigation extends React.Component {


  render() {
    const selectedClass = styles['selected'];
    const linkClass = styles['router-link'];

    return (
      <nav className="navbar navbar-dark bg-info navbar-expand-sm">
        <NavLink className="navbar-brand" to="/list">
          Draw-Sequence
        </NavLink>
        <button
          className="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon" />
        </button>

        <div className="collapse navbar-collapse" id="navbarSupportedContent">
          <ul className="navbar-nav mr-auto">
            <li className={selectedClass + " nav-item"}>
              <NavLink activeClassName={selectedClass} className={linkClass} to="/list">Counter</NavLink>
            </li>
            <li className="nav-item">
              <NavLink activeClassName={selectedClass} className={linkClass} to="/contribute">Contribute</NavLink>
            </li>
            <li className="nav-item">
              <NavLink activeClassName={selectedClass} className={linkClass} to="/about">About</NavLink>
            </li>
          </ul>
        </div>
      </nav>
    );
  }
}

// ng-draw-sequence/src/app/navigation/navigation.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent {
  isCollapsed: boolean;
}

<!-- <nav toggleable="sm" type="dark" variant="info"> -->
<nav class="navbar navbar-expand-sm navbar-dark bg-info">
    <a class="navbar-brand" href="#">Draw-Sequence</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" (click)="isCollapsed = !isCollapsed">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse" [class.collapse]='isCollapsed'>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item nav-link text-dark" outerLinkActive="active-link">
                <a routerLink="/counting-list" routerLinkActive="active-link">Counter</a>
            </li>
            <li class="nav-item nav-link text-light">
                <a routerLink="/contribute" routerLinkActive="active-link">Contribute</a>
            </li>
            <li class="nav-item nav-link text-light">
                <a routerLink="/about" routerLinkActive="active-link">About</a>
            </li>
        </ul>
    </div>
</nav>
