// DrawSequence/ClientApp/partials/Navigation.vue
<template>
  <b-navbar toggleable="sm" type="dark" variant="info">
    <b-navbar-brand href="#">Draw-Sequence</b-navbar-brand>

    <b-navbar-toggle target="nav_collapse" />

    <b-collapse is-nav id="nav_collapse">
      <b-navbar-nav>
        <router-link to="/counter" class="nav-link">Counter</router-link>
        <router-link to="/add" class="nav-link">Contribute</router-link>
        <router-link to="/about" class="nav-link">About</router-link>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<script>
export default {};
</script>

// ng-draw-sequence/src/app/navigation/navigation.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent {
  isCollapsed: boolean;
}

<!-- <nav toggleable="sm" type="dark" variant="info"> -->
<nav class="navbar navbar-expand-sm navbar-dark bg-info">
    <a class="navbar-brand" href="#">Draw-Sequence</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" (click)="isCollapsed = !isCollapsed">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse" [class.collapse]='isCollapsed'>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item nav-link text-dark" outerLinkActive="active-link">
                <a routerLink="/counting-list" routerLinkActive="active-link">Counter</a>
            </li>
            <li class="nav-item nav-link text-light">
                <a routerLink="/contribute" routerLinkActive="active-link">Contribute</a>
            </li>
            <li class="nav-item nav-link text-light">
                <a routerLink="/about" routerLinkActive="active-link">About</a>
            </li>
        </ul>
    </div>
</nav>
