// DrawSequence/ClientApp/partials/Draw.vue
<template>
  <div>
    <drawing-canvas></drawing-canvas>
    <div>
      <upload-summary :result="lastResult"></upload-summary>
      <b-button
        class="mt-3"
        type="submit"
        variant="info"
        @click="onSubmit($event)"
      >
        <b-spinner v-if="isSubmitting" small type="grow" />
        {{ submitButtonText }}
      </b-button>
    </div>
  </div>
</template>

<script>
import UploadSummary from "@Partials/UploadSummary";
import DrawingCanvas from "@Partials/DrawingCanvas";
import imageApi from "@Api/imageApi";

export default {
  data: function() {
    return {
      lastResult: null,
      isSubmitting: false
    };
  },
  computed: {
    submitButtonText: function() {
      return this.isSubmitting ? "Submitting..." : "Submit";
    }
  },
  methods: {
    async upload(file) {
      const dataModel = new FormData();
      dataModel.append("file", file);

      try {
        this.isSubmitting = true;
        const result = await imageApi.uploadImage(dataModel);
        this.lastResult = result;
        if (result.succeeded) {
          this.$emit("ocr-success", result);
        }
      } catch (err) {
        console.warn(err);
      } finally {
        this.isSubmitting = false;
      }
    },
    async onSubmit(e) {
      e.preventDefault();
      const file = this.createFileToUpload();
      await this.upload(file);
    },
    createFileToUpload() {
      const dataURI = document.querySelector("canvas").toDataURL();
      const byteString = atob(dataURI.split(",")[1]);
      const mimeString = dataURI
        .split(",")[0]
        .split(":")[1]
        .split(";")[0];
      const arrayBuffer = new ArrayBuffer(byteString.length);
      const arr = new Uint8Array(arrayBuffer);
      for (let i = 0; i < byteString.length; i++) {
        arr[i] = byteString.charCodeAt(i);
      }
      return new Blob([arrayBuffer], { type: mimeString });
    }
  },
  components: {
    "upload-summary": UploadSummary,
    "drawing-canvas": DrawingCanvas
  }
};
</script>

<style scoped>
button[type="submit"] {
  margin: 0 auto;
  display: block;
}
</style>

// ng-draw-sequence/src/app/contribute/draw/draw.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { ImageService } from 'src/app/image-service/image.service';
import { PointContainerService } from 'src/app/point-container/point-container.service';

@Component({
  selector: 'app-draw',
  templateUrl: './draw.component.html',
  styleUrls: ['./draw.component.css']
})
export class DrawComponent {

  lastResult: ResponseImageViewModel;
  isSubmitting: boolean;

  get submitButtonText(): string {
    return this.isSubmitting ? 'Submitting...' : 'Submit';
  }

  constructor(private imageService: ImageService, private pointContainerService: PointContainerService) { }

  upload(file) {
    this.isSubmitting = true;
    this.imageService.uploadImage(file, {}).subscribe((result: ResponseImageViewModel) => {
      this.lastResult = result;
      if (result.succeeded) {
        this.pointContainerService.incrementCount();
      }
      this.isSubmitting = false;
    }, err => {
      console.warn(err);
      this.isSubmitting = false;
    });
  }

  onSubmit() {
    const file = this.createFileToUpload();
    this.upload(file);
  }

  createFileToUpload() {
    const dataURI = document.querySelector('canvas').toDataURL();
    const byteString = atob(dataURI.split(',')[1]);
    const mimeString = dataURI
      .split(',')[0]
      .split(':')[1]
      .split(';')[0];
    const arrayBuffer = new ArrayBuffer(byteString.length);
    const arr = new Uint8Array(arrayBuffer);
    for (let i = 0; i < byteString.length; i++) {
      arr[i] = byteString.charCodeAt(i);
    }
    return new Blob([arrayBuffer], { type: mimeString });
  }
}

<div>
  <app-drawing-canvas></app-drawing-canvas>
  <div>
    <app-upload-summary [result]="lastResult"></app-upload-summary>
    <button class="btn btn-info mt-3" type="submit" (click)="onSubmit($event)">
      <span [class.loader]="isSubmitting">{{ submitButtonText }} </span>
    </button>
  </div>
</div>
