// react-draw-sequence/src/components/Contribute.js
import React from "react";
import { NavLink } from 'react-router-dom';
//import styles from  './../styles/contribute.module.css';

export const Contribute = props => {

  return (
    <article className="m-3">
      <h2>Contribute to Draw-Sequence</h2>
      <p>
        Here you can add your number to the sequence, either by posting your own
        image with next number of the sequence, or by drawing it on the panel
        below.{" "}
      </p>
      <p>Next number to draw: &lt;TOOD&gt;.</p>
      <ul className="nav nav-tabs">
        <li className="active nav-item">
          <NavLink activeClassName="active" className="nav-link" to="/contribute/draw">
            Draw
          </NavLink>
        </li>
        <li className="nav-item">
          <NavLink activeClassName="active" className="nav-link" to="/contribute/upload">
            Upload a picture
          </NavLink>
        </li>
      </ul>
    </article>
  );
};

// ng-draw-sequence/src/app/contribute/contribute/contribute.component.ts
import { Component } from '@angular/core';
import { PointContainerService } from 'src/app/point-container/point-container.service';

@Component({
  selector: 'app-contribute',
  templateUrl: './contribute.component.html',
  styleUrls: ['./contribute.component.css']
})
export class ContributeComponent {

  constructor(private pointContainerService: PointContainerService) { }

  get nextToDraw() {
    const count = this.pointContainerService.count;
    if (count !== null) {
      return count + 1;
    } else {
      return '..';
    }
  }

  updateImageCount() {
    this.pointContainerService.updateImageCount();
  }
}

<article class="m-3">
    <h2>Contribute to Draw-Sequence</h2>
    <p>
        Here you can add your number to the sequence, either by posting your own
        image with next number of the sequence, or by drawing it on the panel
        below.
    </p>
    <p>Next number to draw: {{ nextToDraw }}.</p>
    <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
            <a class="nav-link" routerLink="draw" routerLinkActive="active">Draw</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" routerLink="upload" routerLinkActive="active">Upload a picture</a>
        </li>
    </ul>
    <router-outlet (activate)="updateImageCount()" (ocrSucceeded)="console.log('ah');"></router-outlet>
</article>
