// DrawSequence/ClientApp/partials/UploadSummary.vue
<template>
  <div v-if="result" class="mb-2 text-center">
    <ul>
      <li v-for="(message, index) in result.errors" :key="index">
        {{ message }}
      </li>
    </ul>
    <p class="alert" :class="recognizedTextClass">
      {{ recognizedTextMessage }}
    </p>
  </div>
</template>

<script>
export default {
  computed: {
    isRecognizedTextEmpty: function() {
      return !this.result.recognizedText || this.result.recognizedText === "";
    },
    recognizedTextMessage: function() {
      if (this.isRecognizedTextEmpty) {
        return "No text has been recognized.";
      } else {
        return `Recognized text: "${this.result.recognizedText}"`;
      }
    },
    recognizedTextClass: function() {
      if (!this.result) {
        return "";
      } else {
        if (this.result.succeeded) {
          return "alert-success";
        } else {
          if (this.isRecognizedTextEmpty) {
            return "alert-warning";
          } else {
            return "alert-danger";
          }
        }
      }
    }
  },
  props: {
    result: {
      required: false,
      default: null
    }
  }
};
</script>

<style scoped>
p {
  max-width: 60%;
  margin: 0 auto;
}
</style>

// ng-draw-sequence/src/app/contribute/upload-summary-component/upload-summary/upload-summary.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-upload-summary',
  templateUrl: './upload-summary.component.html',
  styleUrls: ['./upload-summary.component.css']
})
export class UploadSummaryComponent {

  @Input() result: ResponseImageViewModel;

  get isRecognizedTextEmpty() {
    return !this.result.recognizedText || this.result.recognizedText === '';
  }

  get recognizedTextMessage() {
    if (this.isRecognizedTextEmpty) {
      return 'No text has been recognized.';
    } else {
      return `Recognized text: "${this.result.recognizedText}"`;
    }
  }

  get recognizedTextClass() {
    if (!this.result) {
      return '';
    } else {
      if (this.result.succeeded) {
        return 'alert-success';
      } else {
        if (this.isRecognizedTextEmpty) {
          return 'alert-warning';
        } else {
          return 'alert-danger';
        }
      }
    }
  }

}

<div *ngIf="result" class="mb-2 text-center">
  <ul>
    <li *ngFor="let message of result.errors">
      {{ message }}
    </li>
  </ul>
  <p class="alert" [class]="recognizedTextClass">
    {{ recognizedTextMessage }}
  </p>
</div>
