// ng-draw-sequence/src/app/contribute/draw/drawing-canvas/drawing-canvas/drawing-canvas.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-drawing-canvas',
  templateUrl: './drawing-canvas.component.html',
  styleUrls: ['./drawing-canvas.component.css']
})
export class DrawingCanvasComponent implements OnInit {

  @ViewChild('canvas') canvas;

  currentColor = 'black';
  drawColor = 'black';
  eraseColor = 'white';
  isDrawing = false;
  context = null;
  canvasOffset = null;
  penSize = 5;
  minPenSize = 1;
  maxPenSize = 40;

  constructor() { }

  ngOnInit() {
    this.context = this.canvas.nativeElement.getContext('2d');
    this.canvasOffset = this.getOffset(this.canvas.nativeElement);
    this.resetCanvas();

    window.addEventListener('resize', () => {
      this.canvasOffset = this.getOffset(this.canvas.nativeElement);
    });
  }

  startDrawing() {
    this.checkTools();
    this.isDrawing = true;
  }

  stopDrawing() {
    this.isDrawing = false;
  }

  stroke(e) {
    if (this.hasTouch(e)) {
      e.preventDefault();
    }

    if (!this.isDrawing) {
      return;
    }

    const pos = this.getCursorPos(e);

    this.context.beginPath();
    this.context.arc(pos.x, pos.y, this.penSize, 0, Math.PI * 2);
    this.context.closePath();
    this.context.fill();
  }

  resetCanvas() {
    const color = this.context.fillStyle;
    this.context.fillStyle = 'white';
    this.context.fillRect(0, 0, 300, 200);
    this.context.fillStyle = color;

    this.currentColor = this.drawColor;
  }

  hasTouch(e) {
    return e.touches && e.touches[0];
  }

  getCursorPos(e) {
    if (this.hasTouch(e)) {
      return {
        x: e.touches[0].clientX - this.canvasOffset.left,
        y: e.touches[0].clientY - this.canvasOffset.top
      };
    } else {
      return {
        x: e.clientX - this.canvasOffset.left,
        y: e.clientY - this.canvasOffset.top
      };
    }
  }

  getOffset(elem) {
    let offset = null;
    if (elem) {
      offset = { left: 0, top: 0 };
      do {
        offset.top += elem.offsetTop;
        offset.left += elem.offsetLeft;
        elem = elem.offsetParent;
      } while (elem);
    }
    return offset;
  }

  checkTools() {
    this.context.fillStyle = this.currentColor;
    if (this.penSize < this.minPenSize) {
      this.penSize = this.minPenSize;
    }
    else if (this.penSize > this.maxPenSize) {
      this.penSize = this.maxPenSize;
    }
  }
}

<div class="row" id="main-container">
  <div class="col-sm-9 mx-auto">
    <canvas width="300" height="200" #canvas (mousedown)="startDrawing()" (mouseleave)="stopDrawing()"
      (mouseup)="stopDrawing()" (mousemove)="stroke($event)"></canvas>
  </div>

  <div class="col-sm-3 mx-auto row" id="drawing-tools">
    <div class="col-sm-12 col-4 mb-0">

      <div>
        <input class="form-check-label" type="radio" name="currentColorChoice" [(ngModel)]="currentColor" [value]="drawColor" id="drawColorChoice">
        <label for="drawColorChoice">Draw</label>
      </div>
      <div>
        <input class="form-check-label" type="radio" name="currentColorChoice" [(ngModel)]="currentColor" [value]="eraseColor" id="eraseColorChoice">
        <label for="eraseColorChoice">Erase</label>
      </div>
    </div>

    <div class="col-sm-12 col-4 px-0">
      <label for="penSizeInput">Pen size</label>
      <input id="penSizeInput" type="number" [min]="minPenSize" [max]="maxPenSize" [(ngModel)]="penSize" />
    </div>

    <button class="btn btn-info col-sm-12 col-4" id="clearButton" (click)="resetCanvas()">
      Clear
    </button>
  </div>
</div>

// react-draw-sequence/src/components/DrawingCanvas.js
import React from "react";

class DrawingCanvas extends React.Component {
  drawColor = "black";
  eraseColor = "white";
  minPenSize = 1;
  maxPenSize = 40;

  constructor(props) {
    super(props);
    this.state = {
      currentColor: this.drawColor,
      isDrawing: false,
      canvasOffset: null,
      penSize: 5
    };

    this.startDrawing = this.startDrawing.bind(this);
    this.stopDrawing = this.stopDrawing.bind(this);
    this.stroke = this.stroke.bind(this);
    this.setPenSize = this.setPenSize.bind(this);
    this.resetCanvas = this.resetCanvas.bind(this);
  }

  componentDidMount() {
    this.setState({ canvasOffset: this.getOffset(this.props.canvasRef.current) }, () => {
      this.resetCanvas();
    });

    window.addEventListener("resize", () => {
      this.setState({ canvasOffset: this.getOffset(this.props.canvasRef.current) });
    });
  }

  setPenSize(e) {
    const penSize = Math.max(Math.min(e.target.value, this.maxPenSize), this.minPenSize);
    this.setState({ penSize })
  }

  startDrawing() {
    this.setState({ isDrawing: true });
  }

  stopDrawing() {
    this.setState({ isDrawing: false });
  }

  stroke(e) {
    if (this.hasTouch(e)) {
      e.preventDefault();
    }
    if (!this.state.isDrawing) return;

    const pos = this.getCursorPos(e);
    const context = this.getCanvasContext();

    context.fillStyle = this.state.currentColor;
    context.beginPath();
    context.arc(pos.x, pos.y, this.state.penSize, 0, Math.PI * 2);
    context.closePath();
    context.fill();
  }

  resetCanvas() {
    const context = this.getCanvasContext();
    const color = context.fillStyle;

    context.fillStyle = "white";
    context.fillRect(0, 0, 300, 200);
    context.fillStyle = color;

    this.setState({ currentColor: this.drawColor });
  }

  hasTouch(e) {
    return e.touches && e.touches[0];
  }

  getCursorPos(e) {
    if (this.hasTouch(e)) {
      return {
        x: e.touches[0].clientX - this.state.canvasOffset.left,
        y: e.touches[0].clientY - this.state.canvasOffset.top
      };
    } else {
      return {
        x: e.clientX - this.state.canvasOffset.left,
        y: e.clientY - this.state.canvasOffset.top
      };
    }
  }

  getOffset(elem) {
    let offset = null;
    if (elem) {
      offset = { left: 0, top: 0 };
      do {
        offset.top += elem.offsetTop;
        offset.left += elem.offsetLeft;
        elem = elem.offsetParent;
      } while (elem);
    }
    return offset;
  }

  getCanvasContext() {
    return this.props.canvasRef.current.getContext("2d");
  }

  render() {
    return (
      <section className="row" id="main-container">
        <div className="col-sm-9 mx-auto">
          <canvas
            ref={this.props.canvasRef}
            width="300"
            height="200"
            onMouseDown={this.startDrawing}
            onMouseLeave={this.stopDrawing}
            onMouseUp={this.stopDrawing}
            onMouseMove={this.stroke}
          />
        </div>

        <div className="col-sm-3 mx-auto row" id="drawing-tools">
          <div className="col-sm-12 col-4 mb-0">
            <div className="custom-control custom-radio">
              <input
                className="custom-control-input"
                type="radio"
                id="drawColor"
                name="currentColor"
                value={this.drawColor}
                checked={this.state.currentColor === this.drawColor}
                onChange={e => this.setState({ currentColor: e.target.value })}
              />
              <label className="custom-control-label" htmlFor="drawColor">
                Draw
              </label>
            </div>
            <div className="custom-control custom-radio">
              <input
                className="custom-control-input"
                type="radio"
                id="eraseColor"
                name="currentColor"
                value={this.eraseColor}
                checked={this.state.currentColor === this.eraseColor}
                onChange={e => this.setState({ currentColor: e.target.value })}
              />
              <label className="custom-control-label" htmlFor="eraseColor">
                Erase
              </label>
            </div>
          </div>

          <div className="form-group">
            <label className="col-sm-12 col-4 px-0" htmlFor="penSizeInput">
              Pen size
            </label>
            <input
              className="form-control"
              id="penSizeInput"
              type="number"
              min={this.minPenSize}
              max={this.maxPenSize}
              value={this.state.penSize}
              onChange={this.setPenSize}
            />
          </div>

          <button
            variant="info" 
            className="btn btn-info col-sm-12 col-4"
            onClick={this.resetCanvas}
            id="clear-button">
            Clear
          </button>
        </div>
      </section>
    );
  }
}

export default React.forwardRef((props, ref) => <DrawingCanvas canvasRef={ref} {...props}/>);
