// DrawSequence/ClientApp/partials/Draw.vue
<template>
  <div>
    <drawing-canvas></drawing-canvas>
    <div>
      <upload-summary :result="lastResult"></upload-summary>
      <b-button
        class="mt-3"
        type="submit"
        variant="info"
        @click="onSubmit($event)"
      >
        <b-spinner v-if="isSubmitting" small type="grow" />
        {{ submitButtonText }}
      </b-button>
    </div>
  </div>
</template>

<script>
import UploadSummary from "@Partials/UploadSummary";
import DrawingCanvas from "@Partials/DrawingCanvas";
import imageApi from "@Api/imageApi";

export default {
  data: function() {
    return {
      lastResult: null,
      isSubmitting: false
    };
  },
  computed: {
    submitButtonText: function() {
      return this.isSubmitting ? "Submitting..." : "Submit";
    }
  },
  methods: {
    async upload(file) {
      const dataModel = new FormData();
      dataModel.append("file", file);

      try {
        this.isSubmitting = true;
        const result = await imageApi.uploadImage(dataModel);
        this.lastResult = result;
        if (result.succeeded) {
          this.$emit("ocr-success", result);
        }
      } catch (err) {
        console.warn(err);
      } finally {
        this.isSubmitting = false;
      }
    },
    async onSubmit(e) {
      e.preventDefault();
      const file = this.createFileToUpload();
      await this.upload(file);
    },
    createFileToUpload() {
      const dataURI = document.querySelector("canvas").toDataURL();
      const byteString = atob(dataURI.split(",")[1]);
      const mimeString = dataURI
        .split(",")[0]
        .split(":")[1]
        .split(";")[0];
      const arrayBuffer = new ArrayBuffer(byteString.length);
      const arr = new Uint8Array(arrayBuffer);
      for (let i = 0; i < byteString.length; i++) {
        arr[i] = byteString.charCodeAt(i);
      }
      return new Blob([arrayBuffer], { type: mimeString });
    }
  },
  components: {
    "upload-summary": UploadSummary,
    "drawing-canvas": DrawingCanvas
  }
};
</script>

<style scoped>
button[type="submit"] {
  margin: 0 auto;
  display: block;
}
</style>

// react-draw-sequence/src/components/Draw.js
import React from "react";
import DrawingCanvas from "./DrawingCanvas";
import { ImageService } from './../services/image';
import { connect } from 'react-redux';
import UploadSummary from "./UploadSummary";
import { setMaxImagesCount } from "../actions/imageActions";

class Draw extends React.Component {
  
  constructor(props) {
    super(props);
    this.state = {
      isUploading: false,
      lastResult: null,
      submitButtonText: "Submit"
    };

    this.imageService = new ImageService();

    this.submit = this.submit.bind(this);
  }

  async submit(e) {
    e.preventDefault();
    const file = this.createFileToUpload();
    await this.upload(file);
  }

  async upload(file) {
    this.setState({lastResult: null});
    const dataModel = new FormData();
    dataModel.append("file", file);

    try {
      this.setState({isUploading: true});
      const result = await this.imageService.uploadImage(dataModel);
      this.setState({lastResult: result});
      if (result.succeeded) {
        this.props.dispatch(setMaxImagesCount(this.props.imageContainer.maxImagesCount + 1));
      }
    } catch (err) {
      console.warn(err);
    } finally {
      this.setState({isUploading: false});
    }
  }
  
  createFileToUpload() {
    const dataURI = document.querySelector("canvas").toDataURL();
    const byteString = atob(dataURI.split(",")[1]);
    const mimeString = dataURI
      .split(",")[0]
      .split(":")[1]
      .split(";")[0];
    const arrayBuffer = new ArrayBuffer(byteString.length);
    const arr = new Uint8Array(arrayBuffer);
    for (let i = 0; i < byteString.length; i++) {
      arr[i] = byteString.charCodeAt(i);
    }
    return new Blob([arrayBuffer], { type: mimeString });
  }

  render() {
    return (
      <section>
        <DrawingCanvas />
        <div>
          <UploadSummary result={this.state.lastResult} />

          <button
            className="btn btn-info mt-3"
            type="submit"
            variant="info"
            onClick={this.submit}
          >
            {/* <b-spinner v-if="isSubmitting" small type="grow" /> */}
            {this.state.submitButtonText}
          </button>
        </div>
      </section>
    );
  }
};

function mapStateToProps() {
  return (state) => {
    return { 
      imageContainer: state.image
     };
  };
}

export default connect(mapStateToProps())(Draw);
