// ng-draw-sequence/src/app/foot/foot.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../administration/auth-service/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-foot',
  templateUrl: './foot.component.html',
  styleUrls: ['./foot.component.css']
})
export class FootComponent {

  get isLoggedIn() {
    return this.authService.isLoggedIn();
  }

  constructor(private authService: AuthService, private router: Router) { }

  logout() {
    this.authService.logout();
    this.router.navigateByUrl('/couting-list');
  }

}

<footer class="footer mt-auto py-3">
  <div class="container">
    <a *ngIf="!isLoggedIn; else authenticatedView" routerLink="/login" class="d-block text-center">Admin Login</a>
    <ng-template #authenticatedView>
      <div class="text-center">
        <a routerLink="/manage" class="mr-1">Admin Panel</a>
        <a href="#" target="_self" preventDefault (click)="logout()">Log out</a>
      </div>
    </ng-template>
  </div>
</footer>

// react-draw-sequence/src/components/Foot.js
import React from "react";
import { Link } from "react-router-dom";
import { withRouter } from "react-router-dom";
import AuthService from "./../services/auth";
import { connect } from "react-redux";

class Foot extends React.Component {
  logout() {
    AuthService.logOut(this.props.dispatch);
    this.props.history.push("/list");
  }

  render() {
    const isLoggedIn = this.props.isLoggedIn;

    return (
      <footer className="footer mt-auto py-3">
        <div className="container">
          {isLoggedIn && (
            <span className="d-block text-center">
              <Link to="/admin-list" className="mr-2">
                Admin Panel
              </Link>
              {/* eslint-disable-next-line */}
              <a href="#" onClick={() => this.logout()}>
                Log out
              </a>
            </span>
          )}
          {!isLoggedIn && (
            <Link to="/login" className="d-block text-center">
              Admin Login
            </Link>
          )}
        </div>
      </footer>
    );
  }
}

function mapStateToProps() {
  return state => {
    return {
      isLoggedIn: state.auth.isLoggedIn
    };
  };
}

export default connect(mapStateToProps())(withRouter(Foot));
