// DrawSequence/ClientApp/partials/Upload.vue
<template>
  <div class="main-container">
    <form method="POST" enctype="multipart/form-data" class="mb-2">
      <b-form-file
        v-model="file"
        :state="Boolean(file)"
        accept="image/*"
        @change="fileInputChanged"
        placeholder="Choose a file..."
        drop-placeholder="Drop file here..."
      />
    </form>
    <upload-summary :result="lastResult"></upload-summary>
    <section class="my-3" v-if="lastResult && !lastResult.succeeded">
      <h5>Advanced options</h5>
      <input type="checkbox" v-model="useWhiteList" />
      <label for="checkbox">Recognize only numbers</label>
      <br />
      <input type="checkbox" v-model="recognizeOnlyTarget" />
      <label for="checkbox">Try to recognize only target number</label>
    </section>
    <b-button
      type="submit"
      variant="info"
      @click="onSubmit($event)"
      :disabled="!file"
    >
      <b-spinner v-if="isSubmitting" small type="grow" />
      {{ submitButtonText }}
    </b-button>
  </div>
</template>

<script>
import UploadSummary from "@Partials/UploadSummary";
import imageApi from "@Api/imageApi";

const MAX_FILE_SIZE_MB = 2;
const MAX_FILE_SIZE_B = MAX_FILE_SIZE_MB * 1024 * 1024;

export default {
  data: function() {
    return {
      file: null,
      useWhiteList: false,
      recognizeOnlyTarget: false,
      lastResult: null,
      isSubmitting: false
    };
  },
  methods: {
    fileInputChanged() {
      this.lastResult = null;
      this.resetOptions();
    },
    async upload(file) {
      const dataModel = new FormData();
      dataModel.append("file", file);
      const params = {
        recognizeOnlyTarget: this.recognizeOnlyTarget,
        whitelistDigits: this.useWhiteList
      };

      try {
        this.isSubmitting = true;
        const result = await imageApi.uploadImage(dataModel, params);
        this.lastResult = result;
        if (result.succeeded) {
          this.resetOptions();
          this.$emit("ocr-success", result);
        }
      } catch (err) {
        console.warn(err);
      } finally {
        this.isSubmitting = false;
      }
    },
    resetOptions() {
      this.useWhiteList = false;
      this.recognizeOnlyTarget = false;
    },
    async onSubmit(e) {
      e.preventDefault();
      if (this.file.size > MAX_FILE_SIZE_B) {
        alert(`File size exceeded! Max file size: ${MAX_FILE_SIZE_MB} MB.`);
        this.file = null;
      } else {
        await this.upload(this.file);
      }
    }
  },
  computed: {
    submitButtonText: function() {
      if (this.isSubmitting) {
        return "Submitting...";
      } else {
        if (this.lastResult && !this.lastResult.succeeded) {
          return "Try again";
        } else {
          return "Submit";
        }
      }
    }
  },
  components: {
    "upload-summary": UploadSummary
  }
};
</script>

<style scoped>
.main-container {
  margin: 0 auto;
  max-width: 300px;
}

input[type="file"] {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

button[type="submit"] {
  margin: 0 auto;
  display: block;
}
</style>

// react-draw-sequence/src/components/Upload.js
import React from "react";
import UploadSummary from "./UploadSummary";
import { setMaxImagesCount } from "./../actions/imageActions";
import { connect } from "react-redux";
import { ImageService } from "./../services/image";

const MAX_FILE_SIZE_MB = 2;
const MAX_FILE_SIZE_B = MAX_FILE_SIZE_MB * 1024 * 1024;

class Upload extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isUploading: false,
      lastResult: null,
      submitButtonText: "Submit",
      file: null,
      useWhiteList: false,
      recognizeOnlyTarget: false
    };

    this.imageService = new ImageService();

    this.submit = this.submit.bind(this);
    this.fileInputChanged = this.fileInputChanged.bind(this);
  }

  fileInputChanged(e) {
    this.setState({ file: e.target.files[0] });
    this.setState({ lastResult: null });
    this.resetOptions();
  }

  resetOptions() {
    this.setState({
      useWhiteList: false,
      recognizeOnlyTarget: false
    });
  }

  async submit(e) {
    e.preventDefault();
    if (this.state.file.size > MAX_FILE_SIZE_B) {
      alert(`File size exceeded! Max file size: ${MAX_FILE_SIZE_MB} MB.`);
      this.setState({ file: null });
    } else {
      await this.upload(this.state.file);
    }
  }

  async upload(file) {
    const dataModel = new FormData();
    dataModel.append("file", file);
    const params = {
      recognizeOnlyTarget: this.state.recognizeOnlyTarget,
      whitelistDigits: this.state.useWhiteList
    };

    try {
      this.setState({ isUploading: true });
      const result = await this.imageService.uploadImage(dataModel, params);
      this.setState({ lastResult: result });
      if (result.succeeded) {
        this.resetOptions();
        this.props.dispatch(
          setMaxImagesCount(this.props.imageContainer.maxImagesCount + 1)
        );
      }
    } catch (err) {
      console.warn(err);
    } finally {
      this.setState({ isUploading: false });
    }
  }

  submitButtonText() {
    if (this.isSubmitting) {
      return "Submitting...";
    } else {
      if (this.lastResult && !this.lastResult.succeeded) {
        return "Try again";
      } else {
        return "Submit";
      }
    }
  }

  render() {
    return (
      <section>
        <form
          method="POST"
          encType="multipart/form-data"
          className="m2 file-input-form"
        >
          <div className="custom-file">
            <input
              type="file"
              className="custom-file-input"
              id="validatedCustomFile"
              required
              onChange={this.fileInputChanged}
              accept="image/*"
            />

            {!this.state.file && (
              <label className="custom-file-label">Choose a file...</label>
            )}
            {this.state.file && (
              <label className="custom-file-label">
                {this.state.file.name}
              </label>
            )}
            <div className="invalid-feedback">
              Example invalid custom file feedback
            </div>
          </div>
        </form>
        <UploadSummary result={this.state.lastResult} />
        {this.state.lastResult && !this.state.lastResult.succeeded && (
          <section className="my-3 mb-2 text-center" v-if="lastResult && !lastResult.succeeded">
            <h5>Advanced options</h5>
            <input type="checkbox" v-model="useWhiteList" />
            <label htmlFor="checkbox">Recognize only numbers</label>
            <br />
            <input type="checkbox" v-model="recognizeOnlyTarget" />
            <label htmlFor="checkbox">
              Try to recognize only target number
            </label>
          </section>
        )}
        <button
          className="btn btn-info"
          type="submit"
          variant="info"
          onClick={this.submit}
          disabled={!this.state.file}
        >
          {/* <spinner v-if="isSubmitting" small type="grow" /> */}
          {this.state.submitButtonText}
        </button>
      </section>
    );
  }
}

function mapStateToProps() {
  return state => {
    return {
      imageContainer: state.image
    };
  };
}

export default connect(mapStateToProps())(Upload);
